#!/bin/sh

passfile="/tmp/chrome-passwords-`date +%Y%m%d`.txt"


echo "##############################################################################"
echo
echo "                        Setup user data synchronization"
echo "                             and wait few minutes"
echo
echo "##############################################################################"


google-chrome --user-data-dir=/tmp/chrome-tmp --password-store=basic


cd /tmp/chrome-tmp/Default

sqlite3 -header -csv -separator "," 'Login Data' "SELECT * FROM logins" > $passfile


echo "##############################################################################"
echo
echo "                        Check  $passfile"
echo "                        gpg -c $passfile"
echo
echo "##############################################################################"
